buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.10.0'
        classpath 'com.google.gms:google-services:4.3.15'
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
//        maven {
//            url  "https://phonepe.mycloudrepo.io/public/repositories/phonepe-intentsdk-android"
//        }
    }
}


rootProject.buildDir = "../build"
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(":app")
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}


//Unhandled exception:
//FileSystemException: writeFrom failed, path = 'C:\Users\ravin\AppData\Local\Temp\flutter_tools.50e3c2e1\flutter_tool.cd779d29\app.dill' (OS Error: There is not enough space on the
//        disk.
